#!/usr/bin/bash
tail -1 current-output/chunk-00.log
tail -1 current-output/chunk-01.log
tail -1 current-output/chunk-02.log
tail -1 current-output/chunk-03.log
tail -1 current-output/chunk-04.log
tail -1 current-output/chunk-05.log
tail -1 current-output/chunk-06.log
tail -1 current-output/chunk-07.log
tail -1 current-output/chunk-08.log
tail -1 current-output/chunk-09.log
tail -1 current-output/chunk-10.log
tail -1 current-output/chunk-11.log
tail -1 current-output/chunk-12.log
tail -1 current-output/chunk-13.log
tail -1 current-output/chunk-14.log
tail -1 current-output/chunk-15.log
tail -1 current-output/chunk-16.log
tail -1 current-output/chunk-17.log
tail -1 current-output/chunk-18.log
tail -1 current-output/chunk-19.log
tail -1 current-output/chunk-20.log
tail -1 current-output/chunk-21.log
tail -1 current-output/chunk-22.log
tail -1 current-output/chunk-23.log
tail -1 current-output/chunk-24.log
tail -1 current-output/chunk-25.log
tail -1 current-output/chunk-26.log
tail -1 current-output/chunk-27.log
tail -1 current-output/chunk-28.log
tail -1 current-output/chunk-29.log
